# Generated by Django 5.0.4 on 2024-06-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User addresses'},
        ),
        migrations.AlterModelOptions(
            name='userprivacy',
            options={'verbose_name_plural': 'User privacies'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy',
        ),
    ]
