# Generated by Django 5.0.4 on 2024-06-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraddress_options_alter_userprivacy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='region',
        ),
    ]
